In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Dropout
from tensorflow.keras.utils import to_categorical, plot_model
from tensorflow.keras.datasets import mnist
import datetime

%load_ext tensorboard

In [16]:
mnist.load_data()

((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [18]:
# load mnist dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# compute the number of labels
num_labels = len(np.unique(y_train))
print(num_labels)
print(y_train[0:5])
# convert to one-hot vector
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)
y_train[0:5]

10
[5 0 4 1 9]


array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [25]:
# print(f"{x_train[0]} : {y_train[0]}")

In [24]:
image_size = x_train.shape[1]
input_size = image_size * image_size
print(input_size)

# resize and normalize
x_train = np.reshape(x_train, [-1, input_size])
x_train = x_train.astype('float32') / 255
x_test = np.reshape(x_test, [-1, input_size])
x_test = x_test.astype('float32') / 255

784


In [4]:
print(y_train[0:5])

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [26]:
# network parameters
batch_size = 128
hidden_units = 256
dropout = 0.45

# model is a 3-layer MLP with ReLU and dropout after each layer
model = Sequential()
model.add(Dense(hidden_units, input_dim=input_size))
model.add(Activation('relu'))
model.add(Dropout(dropout))

model.add(Dense(hidden_units))
model.add(Activation('relu'))
model.add(Dropout(dropout))

model.add(Dense(num_labels))
# this is the output for one-hot vector
model.add(Activation('softmax'))

In [27]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 256)               200960    
_________________________________________________________________
activation (Activation)      (None, 256)               0         
_________________________________________________________________
dropout (Dropout)            (None, 256)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 256)               65792     
_________________________________________________________________
activation_1 (Activation)    (None, 256)               0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                2

In [29]:
# loss function for one-hot vector
# use of adam optimizer
# accuracy is good metric for classification tasks
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

# path = "C:\path\to\output\folder"+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
# tensorflow_callback = tf.keras.callbacks.TensorBoard(log_dir = path,histogram_freq = 1)

# train the network
model.fit(x = x_train,y = y_train, epochs=20, batch_size=batch_size)

Epoch 1/20
469/469 [==============================] - 4s 9ms/step - loss: 0.4286 - accuracy: 0.8675
Epoch 2/20
469/469 [==============================] - 4s 7ms/step - loss: 0.1965 - accuracy: 0.9412
Epoch 3/20
469/469 [==============================] - 3s 7ms/step - loss: 0.1525 - accuracy: 0.9538
Epoch 4/20
469/469 [==============================] - 3s 7ms/step - loss: 0.1304 - accuracy: 0.9603
Epoch 5/20
469/469 [==============================] - 3s 7ms/step - loss: 0.1161 - accuracy: 0.9646
Epoch 6/20
469/469 [==============================] - 4s 8ms/step - loss: 0.1055 - accuracy: 0.9678
Epoch 7/20
469/469 [==============================] - 3s 6ms/step - loss: 0.0956 - accuracy: 0.9712
Epoch 8/20
469/469 [==============================] - 3s 6ms/step - loss: 0.0856 - accuracy: 0.9732
Epoch 9/20
469/469 [==============================] - 3s 7ms/step - loss: 0.0825 - accuracy: 0.9748
Epoch 10/20
469/469 [==============================] - 4s 8ms/step - loss: 0.0790 - accuracy: 0.9750

In [30]:
# validate the model on test dataset to determine generalization
loss,acc = model.evaluate(x_test,y_test,batch_size=batch_size,verbose=0)
print("\nTest accuracy: %.1f%%" % (100.0 * acc))

# %tensorboard --logdir=logs/fit


Test accuracy: 98.3%
