In [37]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
import numpy as np

In [22]:
sentences = [
    'I am sleeping',
    'I am playing',
    'I am walking on road',
    'I am eating'
]

In [23]:
tokenize = Tokenizer(num_words = 100)

tokenize.fit_on_texts(sentences)

word_index = tokenize.word_index

In [24]:
print(word_index)

{'i': 1, 'am': 2, 'sleeping': 3, 'playing': 4, 'walking': 5, 'on': 6, 'road': 7, 'eating': 8}


In [25]:
sequences = tokenize.texts_to_sequences(sentences)
print(sequences)

[[1, 2, 3], [1, 2, 4], [1, 2, 5, 6, 7], [1, 2, 8]]


In [28]:
import tensorflow as tf
from tensorflow import keras


from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

sentences = [
    'I love my dog',
    'I love my cat',
    'You love my dog!',
    'Do you think my dog is cool!'
]

tokenizer = Tokenizer(num_words = 100, oov_token="<OOV>")
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index

sequences = tokenizer.texts_to_sequences(sentences)

padded = pad_sequences(sequences, maxlen=5)
print("\nWord Index = " , word_index)
print("\nSequences = " , sequences)
print("\nPadded Sequences:")
print(padded)




# Try with words that the tokenizer wasn't fit to
test_data = [
    'i really love my dog',
    'my dog loves my manatee'
]

test_seq = tokenizer.texts_to_sequences(test_data)
print("\nTest Sequence = ", test_seq)

padded = pad_sequences(test_seq, padding = "post",maxlen=10)
print("\nPadded Test Sequence: ")
print(padded)


Word Index =  {'<OOV>': 1, 'my': 2, 'love': 3, 'dog': 4, 'i': 5, 'you': 6, 'cat': 7, 'do': 8, 'think': 9, 'is': 10, 'cool': 11}

Sequences =  [[5, 3, 2, 4], [5, 3, 2, 7], [6, 3, 2, 4], [8, 6, 9, 2, 4, 10, 11]]

Padded Sequences:
[[ 0  5  3  2  4]
 [ 0  5  3  2  7]
 [ 0  6  3  2  4]
 [ 9  2  4 10 11]]

Test Sequence =  [[5, 1, 3, 2, 4], [2, 4, 1, 2, 1]]

Padded Test Sequence: 
[[5 1 3 2 4 0 0 0 0 0]
 [2 4 1 2 1 0 0 0 0 0]]


In [14]:
import json
dataset = [json.loads(line) for line in open('Sarcasm_Headlines_Dataset.json')]

sentences = []
labels = []
urls = []
print(dataset[0:3])
for item in dataset :
    sentences.append(item['headline'])
    labels.append(item['is_sarcastic'])
    urls.append(item['article_link'])

[{'article_link': 'https://www.huffingtonpost.com/entry/versace-black-code_us_5861fbefe4b0de3a08f600d5', 'headline': "former versace store clerk sues over secret 'black code' for minority shoppers", 'is_sarcastic': 0}, {'article_link': 'https://www.huffingtonpost.com/entry/roseanne-revival-review_us_5ab3a497e4b054d118e04365', 'headline': "the 'roseanne' revival catches up to our thorny political mood, for better and worse", 'is_sarcastic': 0}, {'article_link': 'https://local.theonion.com/mom-starting-to-fear-son-s-web-series-closest-thing-she-1819576697', 'headline': "mom starting to fear son's web series closest thing she will have to grandchild", 'is_sarcastic': 1}]


In [17]:
print(urls[0:3])

['https://www.huffingtonpost.com/entry/versace-black-code_us_5861fbefe4b0de3a08f600d5', 'https://www.huffingtonpost.com/entry/roseanne-revival-review_us_5ab3a497e4b054d118e04365', 'https://local.theonion.com/mom-starting-to-fear-son-s-web-series-closest-thing-she-1819576697']


In [69]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer(oov_token = "<OOV>")
tokenizer.fit_on_texts(sentences)
len(word_index)

25637

In [71]:
sequnces = tokenizer.texts_to_sequences(sentences)
padded = pad_sequences(sequnces,padding = 'post')
print(padded[0])

[  308 15115   679  3337  2298    48   382  2576 15116     6  2577  8434
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0]


In [70]:
voab_size = 10000
embedding_dim = 16
max_length = 100
trunc_type = 'post'
padding_type = "post"
oov_tok = "<OOV>"
training_size = 20000

training_sentences = sentences[0:training_size]
training_labels = labels[0:training_size]

testing_sentences = sentences[0:training_size]
testing_labels = labels[training_size:]

"former versace store clerk sues over secret 'black code' for minority shoppers"

In [78]:
tokenizer = Tokenizer(num_words = vocab_size,oov_token=oov_tok)
tokenizer.fit_on_texts(training_sentences)
word_index = tokenizer.word_index

training_sequences = tokenizer.texts_to_sequences(training_sentences)
training_padded = pad_sequences(training_sequences)

testing_sequences = tokenizer.texts_to_sequences(testing_sentences)
testing_padded = pad_sequences(testing_sequences)


In [79]:
training_sequences[0]

[328, 1, 799, 3405, 2404, 47, 389, 2214, 1, 6, 2614, 8863]

In [80]:
training_padded[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,  328,    1,  799, 3405, 2404,
         47,  389, 2214,    1,    6, 2614, 8863])

In [81]:
training_padded = np.array(training_padded)
training_labels = np.array(training_labels)
 
testing_padded = np.array(testing_padded)
testing_labels = np.array(testing_labels)

In [84]:
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size,embedding_dim,input_length = max_length),
    tf.keras.layers.GlobalAveragePooling1D(),
    tf.keras.layers.Dense(24,activation = 'relu'),
    tf.keras.layers.Dense(1,activation = 'sigmoid')
])
model.compile(loss = 'binary_crossentropy',optimizer = 'adam',metrics = ['accuracy'])

In [85]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 100, 16)           160000    
_________________________________________________________________
global_average_pooling1d_3 ( (None, 16)                0         
_________________________________________________________________
dense_6 (Dense)              (None, 24)                408       
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 25        
Total params: 160,433
Trainable params: 160,433
Non-trainable params: 0
_________________________________________________________________


In [86]:
path = "logs2/fit" + datetime.datetime.now().strftime("%Y%m%d - %H%M%S")
tensor_callback = tf.keras.callbacks.TensorBoard(log_dir = path,histogram_freq = 1)

history = model.fit(training_padded,training_labels,epochs = num_epochs,
                    validation_data = (testing_padded,testing_labels),callbacks = [tensor_callback]) 

Epoch 1/30
625/625 [==============================] - 3s 5ms/step - loss: 0.5799 - accuracy: 0.6830 - val_loss: 0.3965 - val_accuracy: 0.8314
Epoch 2/30
625/625 [==============================] - 2s 4ms/step - loss: 0.3168 - accuracy: 0.8720 - val_loss: 0.3434 - val_accuracy: 0.8541
Epoch 3/30
625/625 [==============================] - 3s 5ms/step - loss: 0.2378 - accuracy: 0.9053 - val_loss: 0.3474 - val_accuracy: 0.8495
Epoch 4/30
625/625 [==============================] - 2s 4ms/step - loss: 0.1930 - accuracy: 0.9270 - val_loss: 0.3607 - val_accuracy: 0.8541
Epoch 5/30
625/625 [==============================] - 3s 4ms/step - loss: 0.1621 - accuracy: 0.9398 - val_loss: 0.3870 - val_accuracy: 0.8518
Epoch 6/30
625/625 [==============================] - 2s 4ms/step - loss: 0.1370 - accuracy: 0.9500 - val_loss: 0.4185 - val_accuracy: 0.8480
Epoch 7/30
625/625 [==============================] - 2s 4ms/step - loss: 0.1176 - accuracy: 0.9597 - val_loss: 0.4567 - val_accuracy: 0.8433
Epoch 

In [87]:
%load_ext tensorboard


The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard


In [88]:
%tensorboard --logdir logs2/fit

Reusing TensorBoard on port 6006 (pid 14952), started 1:03:22 ago. (Use '!kill 14952' to kill it.)

In [92]:
sentence = ['granny starting to fear spiders in the garden might be real',]
sequences = tokenizer.texts_to_sequences(sentence)
padded = pad_sequences(sequences,maxlen = max_length,padding = padding_type,truncating = 'post')
print(model.predict(padded))

[[0.89740384]]
